services:
  server:
    build: ./server
    ports:
      - "9990:9990"
    volumes:
      - dwt-bin:/app/bin
      - dwt-etc:/app/etc
    depends_on:
      - dwt-watermarking
      - sharif-wm

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  dwt-watermarking:
    build: ./analyzers/dwtsvd-watermarking
    volumes:
      - dwt-bin:/usr/local/bin
      - dwt-etc:/usr/local/etc

  sharif-wm:
    build: ./analyzers/sharif-wm

volumes:
  dwt-bin:
  dwt-etc:
